version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy

  img-service:
    build: .
    ports:
      - "9090:9090"  # Porta pouco usual para evitar conflitos
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn core.img:app --host 0.0.0.0 --port 9090
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: inoxlink_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inoxlink_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
